### ISSUE TITLE
uploading bundle file

### ISSUE THREAD

**Issue by ardakdemir** [codalab/chalab#129]
When we upload a bundle (.zip) file obtained by using Chalab wizard to Codalab we can create a competition. However, when we unzip the same file and compress it again (without any modification) into a .zip file we get the following error : 

"Oops! There was a problem creating the competition: 
Could not find file in archive, make sure scoring_program, reference_data and logo are set to correct file paths. "
 
Our aim is to modify the bundle created using chalab wizard according to our needs. Yet at this point we are stuck because of this error. We are not making any changes on the bundle downloaded except for zipping and unzipping but we are still getting an error.

Any help would be appreciated.

**Comment by ckcollab** [comment]
You are probably zipping it up with a "root directory" included, so when it is unpacked the files are like so....


```
/root_dir/
/root_dir/competition.yaml
```

As opposed to...

```
/
/competition.yaml
```

Let us know if this isn't the problem, there could be something else wrong.

**Comment by ardakdemir** [comment]
Yes, indeed that was what we had been doing apparently.

Thanks a lot for the reminder.

**Comment by olyerickson** [comment]
We had this exact issue. I think it's a problem; a common approach to compressing a directory is _compressing the directory_, ie selecting the directory and compressing it!

**Comment by olyerickson** [comment]
Another thing that is not very clear (but we figured out via reverse-engineering) is that hierarchical compression is not sufficient, ie that we must first compress `reference_data` and `scoring_program` before artisanally compressing the bundle...
