### ISSUE TITLE
Delete or download challenges from home page

### ISSUE THREAD

**Issue by madclam** [codalab/chalab#46]
We need a way to "clean up" and delete challenges that we no longer want. At the same time it would be great to be able to download challenge bundles from the home page. I suggest the same interface that we have on the page https://competitions.codalab.org/my/datasets/ in Codalab. Add size and multi-delete option.
![delete](https://user-images.githubusercontent.com/7594063/29728455-d321b9f2-898c-11e7-9b8b-fb4d27382c57.png)

**Comment by madclam** [comment]
Cedric already implemented "delete". Only "download" remains. Only compiled challenges should be dowloadable.

**Comment by Tthomas63** [comment]
<img width="1226" alt="screen shot 2017-09-14 at 7 56 29 pm" src="https://user-images.githubusercontent.com/28552312/30464572-1e12da9a-9987-11e7-8577-1aad4fce650c.png">

If a bundle has been built for the current competition a download link now displays next to delete. This will be in the branch `download-delete-from-home` for further testing and then merged in with `develop` for testing on Heroku staging.

The delete function was already completed and in, just changed the styling of the button.

**Comment by madclam** [comment]
There is no indication of file size for the bundle to download on the front page.

**Comment by Tthomas63** [comment]
Merged and implemented.
