### ISSUE TITLE
Put examples under revision control

### ISSUE THREAD

**Issue by madclam** [codalab/chalab#51]
We have examples for:
- data format
- scoring program / metrics
- starting kit format
that could be referenced from the documentation.
Where should we upload them on Github to put them under revision control?
For the moment they are at: https://github.com/codalab/chalab/tree/master/chalab/static/chalab/resource

**Comment by ckcollab** [comment]
I could make a new repo `Codalab/Chalab-Examples`?

**Comment by madclam** [comment]
we'll make a sub-directory of competition-examples in the codalab repo.
