### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by madclam** [codalab/chalab#57]
Does not seem to work.

**Comment by Tthomas63** [comment]
- [x] Fixed template errors 
- [x] Password reset working using SendGrid
- [x] Email verification mandatory to login unless Debug is True

Merged this into the new develop branch. All new features will be in the develop branch for thorough testing/review before being merged with master.

Also setting up a Heroku staging server running the latest develop branch with automatic deploys anytime develop updates at: https://chalab.herokuapp.com/

**Comment by madclam** [comment]
Interestingly, you are asked for a user ID when you sign up, but after when you login you need to provide your email. Is that purposely?

**Comment by Tthomas63** [comment]
This is the default for `allauth` package we're using it looks like. I believe we should be able to change this though

**Comment by madclam** [comment]
When I sign up the first time, it still lets me into the system before the email confirmation.

**Comment by Tthomas63** [comment]
This should be merged and working on the LRI server.
