### ISSUE TITLE
Signup view 

### ISSUE THREAD

**Issue by tritas** [codalab/chalab#6]
Hi, 
Thanks for the time put into making this site.
I've noticed that the signup form raises an incorrect error message when the user already exists:

![staginsignup](https://cloud.githubusercontent.com/assets/11465877/20661352/aa9fdc10-b54e-11e6-93d0-aa2daf3280fe.png)

 I would issue a PR but I haven't found the source of this issue yet.

**Comment by CeVague** [comment]
The problem come from Django. Other peoples have the same problem :
https://stackoverflow.com/questions/3993560/django-how-to-override-unique-together-error-message
https://code.djangoproject.com/ticket/8913 
https://github.com/pennersr/django-allauth/issues/1449

I'm going to figure out how to resolved this issue but it seams that we can do it only by modify Django files.
