### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by madclam** [codalab/chalab#74]
When creating a new challenge from a group template:
![image](https://user-images.githubusercontent.com/7594063/30991420-d4a02344-a459-11e7-94c3-c8fca080bc2d.png)

I got:
![image](https://user-images.githubusercontent.com/7594063/30991392-bcdd2b12-a459-11e7-80ba-f196e0914314.png)

I re-tried and got:
![image](https://user-images.githubusercontent.com/7594063/30991435-eb2b5f5c-a459-11e7-8674-1875b4d4ddd3.png)

Third try it worked.
Another tester working with me had the same problem.
Is this due to Heroku?

**Comment by Tthomas63** [comment]
Unfortunately, yes it seems. We hit the maximum amount of connections for the postgres lite database

```2017-09-28T21:49:21.258870+00:00 app[web.1]: django.db.utils.OperationalError: FATAL:  too many connections for role "yqlalzbscqdpzm"```

I'll see about fixing this and finding a more permanent solution.

**Comment by Tthomas63** [comment]
I reset all connections, this fixes it for now until we hit the limit again

**Comment by madclam** [comment]
The icons have disappeared after restart:
![image](https://user-images.githubusercontent.com/7594063/30992526-1f81935c-a45f-11e7-9e1e-911dd686c274.png)

We have seen this problem before.

**Comment by madclam** [comment]
I guess we hit the limit again:
![image](https://user-images.githubusercontent.com/7594063/30998459-843b31bc-a483-11e7-8777-90a5765e65c2.png)
