### ISSUE TITLE
Metric file does not load

### ISSUE THREAD

**Issue by madclam** [codalab/chalab#75]
I tried to use the third option to upload a metric. The platform the metric into the editor.
![image](https://user-images.githubusercontent.com/7594063/30992274-e14d01b2-a45d-11e7-8b5d-30b1720c70e7.png)

**Comment by madclam** [comment]
I tried both on heroku and LRI, neither work. I think the file does not load at all.

**Comment by madclam** [comment]
Default metrics do not load either:
![image](https://user-images.githubusercontent.com/7594063/30998233-e2562c68-a481-11e7-87fa-7c8c683fad1d.png)

**Comment by Tthomas63** [comment]
The issue with uploading metrics, and loading metrics should be fixed and merged.
