### ISSUE TITLE
Basic test

### ISSUE THREAD

**Issue by madclam** [codalab/chalab#84]
Before moving on to more sophisticated tests, we should pass this test.
1. [Download test file](https://drive.google.com/drive/folders/0B6bFrQ7a9glMTGlFYUhDQ2J6QXc?usp=sharing).
2. Create a new challenge (use the iris.jpg file for logo).
3. Upload the dataset iris_data_split.zip. Check the result in the data page (page 1) is:
![image](https://user-images.githubusercontent.com/7594063/31575269-8658c89a-b097-11e7-814b-f32d8f9eb5e0.png)
and in the split page (page 2):
![image](https://user-images.githubusercontent.com/7594063/31575279-af835294-b097-11e7-8305-5e086c97efdc.png)
4. Go back to the data page and upload the iris_data_no_split.zip file [the difference in NO split). The data page table should be the same. 
5. In page 2, change the proportions of the data split to 80/10/10, the result should be:
![image](https://user-images.githubusercontent.com/7594063/31575305-7d0a0316-b098-11e7-81c1-8168282060fc.png)
6. Go back to the data page (page 1) and re-upload iris_data_split.zip (this is important for the rest of the test). Check the on page 2 the split is again 70/10/20 and cannot be changed.
7. On page 3 (metrics), select one of the default metrics. Check the 3 fields Name, Description, AND Code are changed. 
8. Stay on page 3 (metrics) and upload sample_metric.py.  Check the 3 fields Name, Description, AND Code are changed. The code should correspond to the contents of sample_metric.py.
9. Stay on page 3 (metrics) and select the default metric classification>bac_multiclass (important to the rest of the test) then save.
10. Select dates on the protocol page (page 4) then in page 5 (baseline definition), upload iris_baseline.zip.
11. Make a small change to the documentation (page 6) then go to recap, then "package and publish".
12. In the "package and publish" page, click "build", then "download".
13. Upload the bundle to a server, e.g. http://13.82.145.119/ or http://13.82.145.119/.
14. Check all pages look fine then go to "Participate". Download the starting kit from the "Files" tab and submit it in the "Submit/View results" tab.
15. Check that the score on the leaderboard is
![image](https://user-images.githubusercontent.com/7594063/31575860-8e934712-b0a4-11e7-8955-103601e7c9b3.png)
16. Click on "View" in the column "Detailed results". You should see:
======= Set 1 (Iris_test): score(bac_multiclass)=1.000000000000 =======
BAC (multiclass) --> 1.0
BAC (multilabel) --> 1.0
AUC (multilabel) --> 1.0
PAC (multilabel) --> 0.984161273648
F1  (multiclass) --> 1.0
PAC (multiclass) --> 0.983304692724
Regression ABS   --> 0.983986801242
F1  (multilabel) --> 1.0
Regression R2    --> 0.994662267081

**Comment by Tthomas63** [comment]
Added to the wiki:

https://github.com/codalab/chalab/wiki/Developers:-Basic-Tests
