### ISSUE TITLE
Typo in example metric

### ISSUE THREAD

**Issue by madclam** [codalab/chalab#86]
In the default example metric:

import numpy as np

def example(solution, prediction):
    mse = np.mean((solution-prediction)**2)
    return np.mean(**mss**)

`mss should be replaced by mse.`

**Comment by Tthomas63** [comment]
This should be fixed with the addition of ingestion program! It may possibly still show with the type-o unless we force re-loading of the default metrics.

**Comment by madclam** [comment]
It's fixed in the code. Will be pushed soon.
