### ISSUE TITLE
Ingestion program

### ISSUE THREAD

**Issue by madclam** [codalab/chalab#88]
We need to create a new page to upload the ingestion program, called "Problem":

![image](https://user-images.githubusercontent.com/7594063/31960633-390f4cbc-b8ad-11e7-9778-e8e36f874388.png)

It will look like this:

![image](https://user-images.githubusercontent.com/7594063/31960747-9072538c-b8ad-11e7-9c45-cc6b8a71f00a.png)

Don't forget to attach a help page.

The YAML file and the competition bundle need to be modified accordingly:
```
phases:
  1:
    blah blah
    ingestion_program: ingestion_program_1_2.zip 
    blah blah   
  2:
    blah blah
    ingestion_program: ingestion_program_1_2.zip 
    blah blah   
```

**Comment by Tthomas63** [comment]
This has been added on a new branch and is on the LRI server.
