### ISSUE TITLE
Bug in metric loading

### ISSUE THREAD

**Issue by madclam** [codalab/chalab#89]
On this page:

![image](https://user-images.githubusercontent.com/7594063/31976800-5ac547b2-b8ee-11e7-9ad5-e365c651b7d5.png)

It is possible to upload files starting with # comments, nor with ''' comments, like:
```
'''Examples of organizer-provided metrics.
You can just replace this code by your own.
Make sure to indicate the name of the function that you chose as metric function
in the file metric.txt. E.g. mse_metric, because this file may contain more 
than one function, hence you must specify the name of the function that is your metric.'''

import numpy as np
import scipy as sp

def mse_metric(solution, prediction):
    '''Mean-square error.
    Works even if the target matrix has more than one column'''
    mse = np.mean((solution-prediction)**2)
    return np.mean(mse)
```

**Comment by Tthomas63** [comment]
So If I understand correctly, also look for a description with `'''` triple docstring comments instead of just singular comments `#` ?

**Comment by Tthomas63** [comment]
I am pushing the fix for this to the LRI server right now. The issue was a null reference, added a check to handle it. Triple doc-strings will not be recognized as a description yet.
