### ISSUE TITLE
Competition Image Disappears Randomly

### ISSUE THREAD

**Issue by Tthomas63** [codalab/chalab#96]
Occasionally on the LRI server, the referenced files seem to be deleted or disappear.

IE: apps/media/challenge/<id>/image is no longer a valid reference.

**Comment by madclam** [comment]
We had that last year already. In case: Cedric fixed it once, we can ask him.

**Comment by Tthomas63** [comment]
Docker volumes updated on production:

Now link/mount style instead of `named volumes`. Data should persist from docker container to host volume.
