### ISSUE TITLE
test new features

### ISSUE THREAD

**Issue by madclam** [codalab/chalab#97]
Tyler push to LRI and Isabelle tests

- [x] linking back to already uploaded datasets
- [x] previous and next at top of page
- [x] remove link to starting kit

**Comment by Tthomas63** [comment]
@madclam 

These changes have been pushed to the LRI server and are ready to test

**Comment by madclam** [comment]
![image](https://user-images.githubusercontent.com/7594063/32396186-821721ea-c0a1-11e7-9e3b-f6ed4b5f7eac.png)
"Next" button does not appear on blue background at the top: difficult to spot.

**Comment by madclam** [comment]
In documentations $variables are no longer being replaced:
![image](https://user-images.githubusercontent.com/7594063/32396418-57b7a14e-c0a2-11e7-85a0-2fb8aa4f4c75.png)

![image](https://user-images.githubusercontent.com/7594063/32396433-684d664c-c0a2-11e7-9a2c-e558febf610d.png)

**Comment by Tthomas63** [comment]
@madclam 

Styling for the previous/next buttons fixed, forgot to run collect static!

In regards to the documentation variables issue, do you happen to know if the metric/protocol for the competition was set, or marked as complete? I was able to reproduce this, but only when the the variable it was trying to access was `incomplete`. Setting or completing it so it was marked as `complete` caused the variable to render.
